apiVersion: v1
kind: Pod
metadata:
  name: game-assets
  labels:
    pod-type: game-assets-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: game-assets-server
      image: gcr.io/tsbr-cluster-demo/game:v0
      imagePullPolicy: Never
      env:
        - name: SESSION_NAME
          value: "game-assets-server"
        - name: REACT_APP_MATCHMAKER_SERVICE
          value: "http://matchmaker"
