apiVersion: v1
kind: Pod
metadata:
  name: matchmaker
  # labels:
  #   pod-type: matchmaker-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: matchmaker
      image: gcr.io/tsbr-cluster-demo/matchmaker:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "matchmaker"
        - name: GAME_INSTANCE_MANAGER_SERVICE_HOST
          value: "10.0.15.240"
        - name: GAME_INSTANCE_MANAGER_SERVICE_PORT
          value: "80"
        - name: GAME_INSTANCE_MANAGER_SERVICE
          value: "10.0.15.240:80"
