apiVersion: v1
kind: Pod
metadata:
  name: matchmaker
  labels:
    pod-type: matchmaker-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: matchmaker
      image: gcr.io/tsbr-cluster-demo/matchmaker:v0
      imagePullPolicy: Never
      env:
        - name: GAME_INSTANCE_MANAGER_SERVICE
          value: "http://game_instance_manager"
