apiVersion: v1
kind: Pod
metadata:
  name: game-instance-manager-server
  labels:
    pod-type: game-instance-manager-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: game-instance-manager-server
  containers:
    - name: game-instance-manager-server
      image: gcr.io/tsbr-cluster-demo/game-instance-manager:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "game-instance-manager-server"
        - name: GAME_SERVER_SERVICE_HOST
          value: "34.83.251.24:80"
        - name: GAME_SERVER_SERVICE_PORT
          value: "7008"
        - name: GAME_SERVER_SERVICE
          value: "34.83.251.24:7008"
