apiVersion: v1
kind: Pod
metadata:
  name: game-instance-manager
  labels:
    pod-type: game-instance-manager-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: game-instance-manager
      image: gcr.io/tsbr-cluster-demo/game-instance-manager:v0
      imagePullPolicy: Never
      env:
      - name: GAME_SERVER_SERVICE
        value: "192.168.64.2:8083"
