apiVersion: v1
kind: Service
metadata:
  name: game-instance-manager-service
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    pod-type: game-instance-manager-pod
  clusterIP: 10.51.240.3
