apiVersion: v1
kind: Pod
metadata:
  name: game-server
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: game-server
  containers:
    - name: game-server
      image: gcr.io/tsbr-cluster-demo/game-server:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "game-server"
