apiVersion: v1
kind: Pod
metadata:
  name: game-server
  labels:
    pod-type: game-server-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: game-server
      image: gcr.io/tsbr-cluster-demo/game-server:v0
      imagePullPolicy: Never
      env:
        - name: SESSION_NAME
          value: "game-server"
