# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: matchmaker
# spec:
#   ports:
#   - port: 80
#     targetPort: 8081
#   selector:
#     pod-type: matchmaker-pod
#   type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: matchmaker
  labels:
    pod-type: matchmaker-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: matchmaker
      image: gcr.io/tsbr-cluster-demo/matchmaker:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "matchmaker"
        - name: GAME_INSTANCE_MANAGER_SERVICE_HOST
          value: "10.51.240.3"
        - name: GAME_INSTANCE_MANAGER_SERVICE_PORT
          value: "80"
        - name: GAME_INSTANCE_MANAGER_SERVICE
          value: "10.51.240.3:80"
---
apiVersion: v1
kind: Pod
metadata:
  name: instance-manager
  labels:
    pod-type: game-instance-manager-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: game-instance-manager-server
      image: gcr.io/tsbr-cluster-demo/game-instance-manager:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "game-instance-manager-server"
---
apiVersion: v1
kind: Service
metadata:
  name: game-instance-manager-service
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    pod-type: game-instance-manager-pod
  clusterIP: 10.51.240.3
---
---
apiVersion: v1
kind: Service
metadata:
  name: kube-api-service
spec:
  ports:
  - port: 80
    targetPort: 8084
  selector:
    pod-type: kube-api-pod
  clusterIP: 10.51.240.2
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-api
  labels:
    pod-type: kube-api-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: api
      image: gcr.io/tsbr-cluster-demo/api:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "game-assets-server"
        - name: REACT_APP_MATCHMAKER_SERVICE
          value: "34.82.65.121:80"
---
apiVersion: v1
kind: Pod
metadata:
  name: game-assets
  labels:
    pod-type: game-assets-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  nodeSelector:
    role: apps
  containers:
    - name: game-assets-server
      image: gcr.io/tsbr-cluster-demo/game:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "game-assets-server"
        - name: REACT_APP_MATCHMAKER_SERVICE
          value: "10.51.240.4:80"
---
apiVersion: v1
kind: Service
metadata:
  name: game-assets
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    pod-type: game-assets-pod
  type: LoadBalancer

# scaler pod
