# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: matchmaker
# spec:
#   ports:
#   - port: 80
#     targetPort: 8081
#   selector:
#     pod-type: matchmaker-pod
#   type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: matchmaker
  labels:
    pod-type: matchmaker-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  containers:
    - name: matchmaker
      image: gcr.io/typespeed-br/matchmaker:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "matchmaker"
---
apiVersion: v1
kind: Pod
metadata:
  name: instance-manager
  labels:
    pod-type: game-instance-manager-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  containers:
    - name: game-instance-manager-server
      image: gcr.io/typespeed-br/game-instance-manager:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "game-instance-manager-server"
    - name: game-instance-manager-sidecar
      image: gcr.io/typespeed-br/game-instance-manager-sidecar:v0
      imagePullPolicy: Always
      ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Pod
metadata:
  name: game-assets
  labels:
    pod-type: game-assets-pod
spec:
  hostNetwork: true
  restartPolicy: Never
  containers:
    - name: game-assets-server
      image: gcr.io/typespeed-br/game:v0
      imagePullPolicy: Always
      env:
        - name: SESSION_NAME
          value: "game-assets-server"
        - name: REACT_APP_MATCHMAKER_SERVICE
          value: "34.82.175.234:80"
# scaler pod
